# Required variables:
# PACKAGE_BUILD_IMAGE
# PACKAGE_UPLOAD_IMAGE
# TARGET_SUITE
# DPUT_REPOSITORY_NAME


stages:
  - tests
  - build
  - deploy

tests:
  # See https://git.vaultit.org/Foretagsdeklaration/docker-build-images
  image: registry.vaultit.org/foretagsdeklaration/bolagsfakta-debian-image
  stage: tests
  cache:
    key: "qvarnmr"
    paths:
      - .pip-cache
  variables:
    PIP_CACHE_DIR: .pip-cache/
  script:
    - pip install -r requirements-dev.txt
    - make test

debian_package:
  stage: build
  image: $PACKAGE_BUILD_IMAGE
  script:
    - ./build-debian-package $TARGET_SUITE 1
    - mv ../*.build ../*.changes ../*.dsc ../*.tar.* ../*.deb ./
  artifacts:
    paths:
      - "*.build"
      - "*.changes"
      - "*.dsc"
      - "*.tar.*"
      - "*.deb"

upload_package:
  stage: deploy
  image: $PACKAGE_UPLOAD_IMAGE
  before_script:
    - /bin/decrypt_secrets.sh
  script:
    - debsign -k$GPGKEYID *.changes
    - dput $DPUT_REPOSITORY_NAME *.changes
  only:
    - master
  artifacts:
    paths:
      - "*.changes"
      - "*.dsc"
