#!/bin/bash

# Build dependencies:
#   sudo apt install build-essential python-all debhelper devscripts

# Usage ./build-debian-package TARGET_SUITE BUILD_NUMBER

set -euvo pipefail

TARGET_SUITE="$1"
BUILD_NUMBER="$2"

commit_date="$(git show --pretty='Date: %cD' | sed -n '/^Date: */s///p')"
formatted_commit_date="$(date -u --date="$commit_date" "+%Y%m%dT%H%M")"
commit="$(git log --pretty=oneline HEAD^..HEAD | awk '{print $1}')"

srcpkg="$(awk '/^Source:/ { print $2 }' debian/control)"
upstream_version="$(dpkg-parsechangelog --show-field Version | sed 's/-[^-]*$//').$formatted_commit_date"

# Full version is upstream_version - build_number
full_version="$upstream_version-$BUILD_NUMBER"

echo "srcpkg: $srcpkg"
echo "upstream_version: $upstream_version"
echo "full_version: $full_version"

# Clean up parent directory
mkdir -p dist/debian
rm -f "dist/debian/${srcpkg}"*_*

# Create upstream tarball
git archive HEAD | xz -9 > "dist/debian/${srcpkg}_${upstream_version}.orig.tar.xz"

# Setup changelog
dch -v "$full_version" -D "$TARGET_SUITE" --force-distribution "New build from commit $commit"
dch -r ''

# Build
export VERSION="$upstream_version"
debuild -e VERSION -us -uc

# Store changes file name
echo "${srcpkg}_${full_version}_amd64.changes" > dist/debian/changes_file
